### PR TITLE
Bug fix/ Refined validation for user input for adding grade

### LINKED ISSUE #103: [PE-D][Tester B] The program allows me to add a grade without inputting the course code
## What
When using `addgrade`, the output said that a grade was added even though I left the course code field empty.

## Output
Input: `addgrade c/ cr/4 g/A m/true`

**Expected:** Some type of error message that says that I have to enter a course code

**Actual:**
```
addgrade c/ cr/4 g/A m/true
____________________________________________________________
____________________________________________________________
 OK! Now I have added your record of the course  (4 credits, Grade: A) (Major course)
____________________________________________________________
____________________________________________________________
```

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #107: [PE-D][Tester B] Program accepts negative value credits
## What
When using `addgrade` it allows me to input negative credit for a course.

## Output
After a few `addgrade` inputs this is what I have:
```
____________________________________________________________
____________________________________________________________
 You have studied 4 courses.
 Your total grade points are 60.0
 Number of credits you have studied: 14
 Your GPA is: 4.29
____________________________________________________________
____________________________________________________________
 You have studied 3 major courses.
 Your total major course grade points are 44.0
 Number of credits you have studied: 10
 Your major GPA is: 4.40
____________________________________________________________
____________________________________________________________
```
_Note the the number of total credits and major credits are 14 and 10 respectively_
Now, when I input `addgrade c/CS2113 cr/-4 g/A m/true`
This is the output:
```
____________________________________________________________
____________________________________________________________
 You have studied 5 courses.
 Your total grade points are 40.0
 Number of credits you have studied: 10
 Your GPA is: 4.00
____________________________________________________________
____________________________________________________________
 You have studied 4 major courses.
 Your total major course grade points are 24.0
 Number of credits you have studied: 6
 Your major GPA is: 4.00
____________________________________________________________
____________________________________________________________
```
_Note that the credits are now 10 and 6_

**Expected:** Error message not allowing user to input invalid credit/units value.

## Potential Problem
The user might accidentally add a negative credit value and the result of the GPA would be inaccurate.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #112: [PE-D][Tester B] Allows the ability to add an invalid grade letter then using the gpa command gives an error message
## What
The `addgrade` command allows me to input an invalid grade which doesn't raise any error messages. However, when I then check the `gpa`, it gives me an error message saying I have an invalid grade but there is no command to delete the invalid grade.

## Output
**Input:** `addgrade c/CS2113 cr/4 g/Z m/true`
**Expected:** Error message not allowing user to enter an invalid grade
**Actual:**
```
____________________________________________________________
____________________________________________________________
 OK! Now I have added your record of the course CS2113 (4 credits, Grade: Z) (Major course)
____________________________________________________________
____________________________________________________________
gpa
____________________________________________________________
____________________________________________________________
 You have entered an invalid grade!
____________________________________________________________
____________________________________________________________
```

## Potential Problem and Suggestion
If the user mistakenly entered an invalid grade, they are not able to use the `gpa` command anymore.
- Would it be better to have the grade options as `enum`s?
- If it is allowed to add any grade, despite being valid or invalid, would having a "remove grade" feature improve this functionality?

-------------
Labels: `severity.High` `type.FunctionalityBug`

### LINKED ISSUE #117: [PE-D][Tester B] addgrade command allows to add a non-boolean to the is major course field
## What
When using `addgrade` command, it allows the user to input a non-boolean after `m/` field.

## Ouput
**Input:** `addgrade c/CS2113 cr/4 g/A m/test`
**Expected:** Error message saying that there is an invalid input.
**Actual:**
```
____________________________________________________________
____________________________________________________________
 OK! Now I have added your record of the course CS2113 (4 credits, Grade: A)
____________________________________________________________
____________________________________________________________
```

## Notes
Even though the input is invalid, it does not really effect functionality because gpa checker specifically checks when if the course is a major course and just has it be part of the total gpa otherwise; which doesn't seem to effect functionality.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #128: [PE-D][Tester E] `addgrade` accepts any character as grade input
# 1. Steps to Reproduce

- Launch the Uniflow app.

- Add two modules:

```

insert i/CS2113 n/Software d/Friday f/16:00 t/18:00 s/lecture
insert i/CS2107 n/Introduction d/Thursday f/14:00 t/16:00 s/lecture

```

- Run the command to add a course grade with an invalid grade character:

```

addgrade c/CS2113 cr/4 g/o+ m/true

```

Observe the output.

# 2. Expected Behavior

- The application should validate the `g/` parameter and only accept valid grade values (e.g., A, B+, B, C+, etc.).  
- Any invalid grade input should be rejected with an error message, e.g.:

```

Invalid grade. Please enter a valid grade (A, A-, B+, B, B-, ...).

```

- The course should not be added if the grade is invalid.

# 3. Actual Behavior

- The app accepts any input as a grade, e.g., `o+`.  
- The course is added successfully, even though the grade is invalid.

Example output:

```

OK! Now I have added your record of the course CS2113 (4 credits, Grade: o+) (Major course)

```

Image

# 4. System Information

Java version: 17

OS: macOS 15

# 5. Rationale

- This is a functionality bug because the system does not enforce valid grade constraints.  
- Severity is Medium because incorrect grades can mislead users and affect GPA calculations.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #140: [PE-D][Tester D] Addgrade command constraint
Image

addgrade should be rejecting user invalid input (for example above, g/gg). Current implementation causes gpa command to break which is not ideal.

There is also no removegrade command, so this bricks gpa command permanently.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #143: [PE-D][Tester D] Functionality broken for: gpa
Image

Valid insertion command is given (`insert i/MA1512 n/differential equations d/thursday f/10:00 t/12:00 s/tutorial`)

Valid addgrade command is given (`addgrade c/MA1512 cr/4 g/A m/true`)

gpa command returns:  "You have entered an invalid grade!"

-------------
Labels: `severity.High` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by ycdaniel326**
Added comprehensive validation for user input in Parser's parseAddGradeCommand. 
Invalid user inputs are handled. 

fixes #103
fixes #107
fixes #112
fixes #117
fixes #128
fixes #140
fixes #143

### CODE REVIEW

File: src/main/java/seedu/duke/Parser.java [hunk 1]
```diff
@@ -112,21 +112,52 @@ private static Command parseAddGradeCommand(String command, boolean save) throws
         String code = null;
         int credits = -1;
         String grade = null;
-        //default is not major course if not specified
         boolean isMajor = false;
 
         for (String part : parts) {
             if (part.startsWith("c/")) {
-                code = part.substring(2);
+                code = part.substring(2).trim();
```
Comment (patrykmrozek) [inline src/main/java/seedu/duke/Parser.java]: In relation to my previous comment, you could also remove these magic numbers by using, for example, PREFIX_COURSE.length() or something similar

**Review by patrykmrozek — CHANGES_REQUESTED** [review]
